# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTicker',
            fields=[
                ('stockname', models.CharField(max_length=400)),
                ('stockticker', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
